<a href="https://colab.research.google.com/github/HiwaTase/Machine-Learning/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
!pip install mglearn
import mglearn
import numpy as np
import pandas as pd
from pandas.plotting import scatter_matrix

Collecting mglearn
  Downloading mglearn-0.2.0-py2.py3-none-any.whl (581 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.4/581.4 kB 5.2 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from mglearn) (1.25.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from mglearn) (3.7.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from mglearn) (1.2.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from mglearn) (2.0.3)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from mglearn) (9.4.0)
Requirement already satisfied: cycler in /usr/local/lib/python3.10/dist-packages (from mglearn) (0.12.1)
Requirement already satisfied: imageio in /usr/local/lib/python3.10/dist-packages (from mglearn) (2.31.6)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from mglearn) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->mglearn) (1.2.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->mglearn) (4.53.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->mglearn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->mglearn) (24.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->mglearn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->mglearn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->mglearn) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->mglearn) (2024.1)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->mglearn) (1.11.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->mglearn) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->mglearn) (1.16.0)
Installing collected packages: mglearn
Successfully installed mglearn-0.2.0

In [ ]:
##step 1:Load the data

In [3]:
import pandas as pd

url = 'https://raw.githubusercontent.com/HiwaTase/Machine-Learning/main/healthINS_balanced.csv'

df = pd.read_csv(url)

In [4]:
df.head()

,nohealthins,marst,race2,WKSWORK2,classwkr,empstat,inctot,uhrswork,age,school,cit2,educ_att,female,metro,region,vetstat
0,0,"Married, spouse present",white,NaN,NaN,Not in labor force,36300,0,71,"No, not in school",US cit by birth,HS or GED,0,Not in metro area,Middle Atlantic Division,Veteran
1,0,Widowed,white,NaN,NaN,Not in labor force,12500,0,68,"No, not in school",US cit by birth,Less than HS,1,Central city status unknown,East North Central Div.,Not a veteran
2,0,Widowed,white,40-47 weeks,Works for wages,Employed,24100,32,44,"No, not in school",US cit by birth,Less than HS,1,Not identifiable,South Atlantic Division,Not a veteran
3,0,"Married, spouse absent",latino,NaN,NaN,Not in labor force,10900,0,87,"No, not in school",US cit by birth,Less than HS,1,Central city status unknown,Middle Atlantic Division,Not a veteran
4,0,"Married, spouse present",white,1-13 weeks,Works for wages,Not in labor force,24200,16,77,"No, not in school",US cit by birth,HS or GED,0,Not in metro area,East North Central Div.,Veteran

In [ ]:
##Step 2: Divide into a training set and a testing set

In [5]:

from sklearn.model_selection import train_test_split

X = df.drop('nohealthins', axis=1)
y = df['nohealthins']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

print("Training set target class distribution:")
print(y_train.value_counts())

print("\nTesting set target class distribution:")
print(y_test.value_counts())

Training set target class distribution:
nohealthins
1    29704
0    26184
Name: count, dtype: int64

Testing set target class distribution:
nohealthins
1    7427
0    6546
Name: count, dtype: int64

In [6]:
train_df = pd.concat([X_train, y_train], axis=1)


print("Training set info:")
train_df.info()


print("\nTraining set description:")
train_df.describe()

Training set info:
<class 'pandas.core.frame.DataFrame'>
Index: 55888 entries, 66187 to 69658
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   marst        55888 non-null  object
 1   race2        55888 non-null  object
 2   WKSWORK2     35990 non-null  object
 3   classwkr     42485 non-null  object
 4   empstat      55130 non-null  object
 5   inctot       55888 non-null  int64
 6   uhrswork     55888 non-null  int64
 7   age          55888 non-null  int64
 8   school       55888 non-null  object
 9   cit2         55888 non-null  object
 10  educ_att     55888 non-null  object
 11  female       55888 non-null  int64
 12  metro        55888 non-null  object
 13  region       55888 non-null  object
 14  vetstat      54300 non-null  object
 15  nohealthins  55888 non-null  int64
dtypes: int64(5), object(11)
memory usage: 7.2+ MB

Training set description:

             inctot      uhrswork           age        female   nohealthins
count  5.588800e+04  55888.000000  55888.000000  55888.000000  55888.000000
mean   2.550889e+04     23.928249     42.690846      0.487296      0.531492
std    3.998668e+04     20.709805     17.667903      0.499843      0.499012
min   -1.480000e+04      0.000000     15.000000      0.000000      0.000000
25%    2.800000e+03      0.000000     28.000000      0.000000      0.000000
50%    1.490000e+04     30.000000     42.000000      0.000000      1.000000
75%    3.200000e+04     40.000000     55.000000      1.000000      1.000000
max    1.071000e+06     99.000000     95.000000      1.000000      1.000000

In [ ]:
## Step 4 : Cleaning training data

In [19]:
missing_values = train_df.isnull().sum()
print(missing_values)

marst              0
race2              0
WKSWORK2       19898
classwkr       13403
empstat          758
inctot             0
uhrswork           0
age                0
school             0
cit2               0
educ_att           0
female             0
metro              0
region             0
vetstat         1588
nohealthins        0
dtype: int64

In [ ]:
# Drop the specified columns
train_df.drop(["WKSWORK2", "classwkr", "empstat", "vetstat"], axis=1)

In [20]:

columns_fill = ["inctot", "uhrswork", "age"]


for column in columns_fill:
    median_value = train_df[column].median()
    train_df[column].fillna(median_value, inplace=True)

,marst,race2,inctot,uhrswork,age,school,cit2,educ_att,female,metro,region,nohealthins
66187,Never married/single,white,0,0,35,"No, not in school",US cit by birth,HS or GED,0,Not in metro area,New England Division,1
23380,"Married, spouse present",white,85960,48,58,"No, not in school",US cit by birth,more than BA,0,Not in metro area,Mountain Division,0
27623,Never married/single,white,0,0,15,"Yes, in school",US cit by birth,Less than HS,1,Central city status unknown,Pacific Division,0
9093,"Married, spouse present",white,11500,0,78,"No, not in school",US cit by birth,HS or GED,1,Central city status unknown,South Atlantic Division,0
42479,"Married, spouse present",latino,0,0,42,"Yes, in school",Naturalized,"Some college, no degree",1,"In metro, area, outside central city",Middle Atlantic Division,1
...,...,...,...,...,...,...,...,...,...,...,...,...
28986,"Married, spouse present",white,80000,42,62,"No, not in school",US cit by birth,Bachelor's Degree,1,"In metro, area, outside central city",South Atlantic Division,0
3449,"Married, spouse present",white,42000,40,57,"No, not in school",US cit by birth,Associate's Degree,1,Not in metro area,South Atlantic Division,0
43282,Never married/single,latino,0,0,17,"Yes, in school",Non-citizen,Less than HS,0,"In metro, area, outside central city",Pacific Division,1
69080,"Married, spouse present",black,35000,40,53,"No, not in school",US cit by birth,Bachelor's Degree,1,"In metro, area, outside central city",South Atlantic Division,1
69658,Never married/single,white,0,0,35,"Yes, in school",US cit by birth,"Some college, no degree",0,Central city status unknown,South Atlantic Division,1

In [22]:
train_df.head()

,marst,race2,WKSWORK2,classwkr,empstat,inctot,uhrswork,age,school,cit2,educ_att,female,metro,region,vetstat,nohealthins
66187,Never married/single,white,NaN,Works for wages,Not in labor force,0,0,35,"No, not in school",US cit by birth,HS or GED,0,Not in metro area,New England Division,Not a veteran,1
23380,"Married, spouse present",white,50-52 weeks,Works for wages,Employed,85960,48,58,"No, not in school",US cit by birth,more than BA,0,Not in metro area,Mountain Division,Not a veteran,0
27623,Never married/single,white,NaN,NaN,NaN,0,0,15,"Yes, in school",US cit by birth,Less than HS,1,Central city status unknown,Pacific Division,NaN,0
9093,"Married, spouse present",white,NaN,NaN,Not in labor force,11500,0,78,"No, not in school",US cit by birth,HS or GED,1,Central city status unknown,South Atlantic Division,Not a veteran,0
42479,"Married, spouse present",latino,NaN,Works for wages,Unemployed,0,0,42,"Yes, in school",Naturalized,"Some college, no degree",1,"In metro, area, outside central city",Middle Atlantic Division,Not a veteran,1